module.exports = [
    // May - August, summer themed
    "May 27 - If you could spend one perfect summer evening anywhere, where would you go and what would you do?",
    "May 28 - What is something small that instantly improves your mood during warm weather?",
    "May 29 - What fictional world would be the most fun to explore during summer break?",
    "May 30 - What is a random childhood summer memory you still think about sometimes?",
    "May 31 - What kind of weather makes you want to stay outside as long as possible?",
    "June 1 - If you had a free road trip ticket for one week, where would you go first?",
    "June 2 - What is a food that tastes better when eaten outside?",
    "June 3 - What game always reminds you of summer vacation energy?",
    "June 4 - What is the best late-night snack after staying awake too long?",
    "June 5 - If your life had a summer soundtrack right now, what songs would be on it?",
    "June 6 - What is one hobby that feels more enjoyable during summer?",
    "June 7 - What kind of small adventure would make this summer memorable for you?",
    "June 8 - What is your favorite smell during summer mornings or evenings?",
    "June 9 - If you could instantly master one outdoor activity, what would you pick?",
    "June 10 - What is a movie that perfectly captures summer vibes for you?",
    "June 11 - What is one thing you wish summer lasted longer for?",
    "June 12 - What is the best drink to have on a really hot day?",
    "June 13 - What is something you enjoy more at night than during the day?",
    "June 14 - If you could host the ultimate backyard hangout, what would it include?",
    "June 15 - What is a game mechanic from any game you wish existed in real life?",
    "June 16 - What is one goal you would actually like to finish before summer ends?",
    "June 17 - What place nearby feels underrated but relaxing to visit?",
    "June 18 - What fictional character would be fun to spend a summer vacation with?",
    "June 19 - What is your favorite type of summer storm?",
    "June 20 - What is one thing you enjoy doing with your phone completely put away?",
    "June 21 - What would your dream summer gaming setup look like?",
    "June 22 - What is something that always feels nostalgic no matter how old you get?",
    "June 23 - What is the most peaceful time of day during summer?",
    "June 24 - If you could teleport to one concert or event right now, which would you choose?",
    "June 25 - What is one smell that instantly reminds you of another time in your life?",
    "June 26 - What is a small thing that makes hanging out with friends better?",
    "June 27 - What is one thing you would love to learn purely for fun?",
    "June 28 - If your current mood became a weather forecast, what would it sound like?",
    "June 29 - What is your favorite kind of sunset sky?",
    "June 30 - What is a random internet rabbit hole you enjoyed exploring recently?",
    "July 1 - What is something that always sounds fun in theory but exhausting in practice?",
    "July 2 - What snack disappears fastest whenever you buy it?",
    "July 3 - If you could turn one video game location into a vacation destination, which would you choose?",
    "July 4 - What is the best thing about staying awake way too late during summer?",
    "July 5 - What kind of store could you wander through for hours without getting bored?",
    "July 6 - What is one thing people overcomplicate way too much?",
    "July 7 - What is your favorite kind of random conversation to have with friends?",
    "July 8 - What would your ideal lazy day schedule look like from morning to night?",
    "July 9 - What is a sound that feels weirdly calming to you?",
    "July 10 - What is one thing you would never get tired of talking about?",
    "July 11 - If you could add one harmless superpower to your daily life, what would it be?",
    "July 12 - What is the funniest thing you believed when you were younger?",
    "July 13 - What is one place you always wanted to explore after dark?",
    "July 14 - What kind of weather makes gaming feel extra cozy?",
    "July 15 - What is one thing you appreciate more now than you did a few years ago?",
    "July 16 - What is the perfect food combo that sounds questionable but tastes amazing?",
    "July 17 - What is a fictional creature you wish existed as a harmless pet?",
    "July 18 - What is something you think everyone should experience at least once?",
    "July 19 - If you had to spend a week inside one game, which would be the safest choice?",
    "July 20 - What is your favorite type of random YouTube video to binge?",
    "July 21 - What is one memory that feels oddly cinematic when you think about it?",
    "July 22 - What is the most satisfying part of finishing a long project?",
    "July 23 - What kind of room lighting makes a place instantly feel comfortable?",
    "July 24 - What is one trend you genuinely enjoyed instead of finding annoying?",
    "July 25 - What fictional character would absolutely dominate at running a Discord server?",
    "July 26 - What is the best thing to do when rain ruins your original plans?",
    "July 27 - What is something you thought was boring until you actually tried it?",
    "July 28 - What kind of music fits driving around at night the best?",
    "July 29 - What is one thing that makes a game immediately more replayable?",
    "July 30 - What is the best kind of compliment to receive unexpectedly?",
    "July 31 - If you could relive one day from any summer, which day would you choose?",
    "August 1 - What is one thing you want to improve before the year ends?",
    "August 2 - What is your favorite way to cool down after being outside too long?",
    "August 3 - What is something simple that instantly makes a room feel cozy?",
    "August 4 - If your personality had a color palette, what colors would dominate it?",
    "August 5 - What is one fictional item you wish existed in real life?",
    "August 6 - What is the weirdest food combination you secretly enjoy?",
    "August 7 - What game soundtrack deserves way more attention than it gets?",
    "August 8 - What is one thing you miss about being younger?",
    "August 9 - What is the best part about thunderstorms when you are indoors?",
    "August 10 - What would your dream sleep schedule actually look like?",
    "August 11 - What is a tiny inconvenience that annoys you more than it should?",
    "August 12 - What is one piece of advice that unexpectedly stuck with you?",
    "August 13 - If your current life became a TV show, what genre would it be?",
    "August 14 - What is the most satisfying smell after it rains?",
    "August 15 - What kind of fictional side quest would you immediately accept?",
    "August 16 - What is one thing you could talk about for hours without preparation?",
    "August 17 - What is your favorite type of late-night conversation?",
    "August 18 - What is something you wish existed near where you live?",
    "August 19 - What is the best feeling after a long exhausting day?",
    "August 20 - If you could instantly replay one game for the first time again, which would it be?",
    "August 21 - What is one thing that makes a friendship feel effortless?",
    "August 22 - What kind of environment helps you focus the most?",
    "August 23 - What is one oddly specific fear or concern you have?",
    "August 24 - What is the coolest sounding word you know?",
    "August 25 - What is one thing you wish schools taught more realistically?",
    "August 26 - What is your favorite excuse to stay indoors all day?",
    "August 27 - What is a small purchase that genuinely improved your daily life?",
    "August 28 - What kind of fictional shop would you visit constantly?",
    "August 29 - What is something that instantly ruins your motivation?",
    "August 30 - What is the best thing about cold drinks on hot days?",
    "August 31 - What is one thing you are hoping changes before next summer?",

    // September - October, fall & Halloween themed
    "September 1 - What is your favorite thing about the beginning of fall weather?",
    "September 2 - What kind of hoodie or outfit instantly feels comfortable to wear?",
    "September 3 - What fictional horror setting would you survive the longest in?",
    "September 4 - What is one thing that feels better during cloudy weather?",
    "September 5 - What snack is impossible to eat just one of?",
    "September 6 - What is the best type of spooky game to play late at night?",
    "September 7 - What smell immediately reminds you of autumn?",
    "September 8 - If you owned a small cozy cafe, what would make it unique?",
    "September 9 - What is one harmless conspiracy theory that sounds funny to believe?",
    "September 10 - What kind of rainy day activity feels the most relaxing?",
    "September 11 - What fictional villain actually had a decent point?",
    "September 12 - What is your favorite excuse to avoid going outside?",
    "September 13 - What is one weird dream you still remember clearly?",
    "September 14 - What is the best kind of weather for sleeping?",
    "September 15 - What abandoned-looking place would you explore if it was guaranteed safe?",
    "September 16 - What is one thing that instantly improves a boring day?",
    "September 17 - What is the creepiest sound to hear unexpectedly at night?",
    "September 18 - What kind of Halloween costume idea sounds creative but difficult to pull off?",
    "September 19 - What is one fictional monster you think looks genuinely cool?",
    "September 20 - What is your favorite comfort game when stressed or tired?",
    "September 21 - What is something that used to scare you but no longer does?",
    "September 22 - What type of candle scent would perfectly match your room?",
    "September 23 - What is the ideal snack lineup for a horror movie marathon?",
    "September 24 - What is one mystery from history you wish you could know the truth about?",
    "September 25 - What is your favorite kind of nighttime weather?",
    "September 26 - What fictional universe would be terrifying to live in permanently?",
    "September 27 - What is one oddly satisfying sound you enjoy hearing?",
    "September 28 - What is the perfect balance between chaos and relaxation for a weekend?",
    "September 29 - What is a Halloween candy you think deserves more respect?",
    "September 30 - What is one thing that instantly makes a room feel eerie?",
    "October 1 - What horror game creature would make the worst roommate?",
    "October 2 - What is the best weather for walking outside at night?",
    "October 3 - What fictional haunted house would you willingly spend one night inside?",
    "October 4 - What song sounds even better during colder weather?",
    "October 5 - What is one urban legend that genuinely creeped you out?",
    "October 6 - What is your favorite Halloween decoration style?",
    "October 7 - What is one thing that becomes funnier when you are sleep deprived?",
    "October 8 - What spooky creature design do you think is underrated?",
    "October 9 - What is the ideal setup for a perfect movie night in October?",
    "October 10 - What fictional character would survive a horror movie the easiest?",
    "October 11 - What is your favorite thing about darker evenings during fall?",
    "October 12 - What abandoned building trope in horror games always works on you?",
    "October 13 - What is one thing you would add to make Halloween more exciting?",
    "October 14 - What kind of weather would fit your personality best today?",
    "October 15 - What is the creepiest fictional location you can think of?",
    "October 16 - What snack feels mandatory during horror movies?",
    "October 17 - What is one game mechanic that always increases tension perfectly?",
    "October 18 - What costume from fiction would be fun to recreate in real life?",
    "October 19 - What is your favorite kind of ghost story setup?",
    "October 20 - What random thing irrationally scares you sometimes?",
    "October 21 - What is one thing that instantly ruins the mood in a horror game?",
    "October 22 - What would your ideal haunted attraction include?",
    "October 23 - What fictional world would be terrifying at night but fine during daytime?",
    "October 24 - What is the funniest bad horror movie you have seen?",
    "October 25 - What is your favorite Halloween memory from childhood?",
    "October 26 - What would your personal Halloween theme be this year?",
    "October 27 - What horror movie or game has the best atmosphere overall?",
    "October 28 - What is one thing you secretly enjoy about colder weather?",
    "October 29 - What is the most creative prank or scare you have seen?",
    "October 30 - What spooky creature would actually make a good friend?",
    "October 31 - What is your perfect Halloween night from start to finish?",

    // November - January, winter themed
    "November 1 - What is your favorite excuse to stay wrapped in blankets all day?",
    "November 2 - What hot drink would perfectly describe your personality?",
    "November 3 - What is one thing colder weather makes better?",
    "November 4 - What game feels extra cozy to play during winter evenings?",
    "November 5 - What is your favorite type of cloudy day?",
    "November 6 - What meal feels the most comforting after being outside in the cold?",
    "November 7 - What is something you unexpectedly enjoy about quiet days?",
    "November 8 - What fictional winter location would you actually want to visit?",
    "November 9 - What sound instantly makes you feel relaxed indoors?",
    "November 10 - What is the best kind of lighting for late-night gaming?",
    "November 11 - What is one thing you would improve about winter?",
    "November 12 - What is the coziest possible room setup you can imagine?",
    "November 13 - What random smell reminds you of holidays or family gatherings?",
    "November 14 - What fictional character would be the best cook during winter?",
    "November 15 - What is your favorite type of peaceful scenery?",
    "November 16 - What is one thing you genuinely enjoy doing alone?",
    "November 17 - What song sounds the most nostalgic during cold nights?",
    "November 18 - What is one winter activity you rarely do but always enjoy?",
    "November 19 - What kind of snack belongs at every movie night?",
    "November 20 - What fictional universe would be surprisingly cozy to live in?",
    "November 21 - What is the most relaxing sound to fall asleep to?",
    "November 22 - What is one thing you wish people appreciated more?",
    "November 23 - What is your ideal room temperature during winter?",
    "November 24 - What is something simple that instantly improves your day?",
    "November 25 - What is one random skill you think would be fun to master?",
    "November 26 - What food always feels worth the effort to make?",
    "November 27 - What is your favorite type of conversation to have late at night?",
    "November 28 - What is one thing that always helps you reset mentally?",
    "November 29 - What is your favorite kind of background noise while relaxing?",
    "November 30 - What fictional character would make the funniest holiday guest?",
    "December 1 - What instantly makes a room feel festive or cozy to you?",
    "December 2 - What is your favorite type of winter evening activity?",
    "December 3 - What fictional item would make winter significantly easier?",
    "December 4 - What is the best feeling after coming inside from cold weather?",
    "December 5 - What song or soundtrack fits snowy weather perfectly?",
    "December 6 - What would your dream winter cabin include?",
    "December 7 - What is something you want to improve before the year ends?",
    "December 8 - What is your favorite type of holiday snack or dessert?",
    "December 9 - What fictional world would look amazing covered in snow?",
    "December 10 - What is one thing you accomplished this year that you are proud of?",
    "December 11 - What is your ideal way to spend a cold weekend indoors?",
    "December 12 - What game has the best winter atmosphere?",
    "December 13 - What is one thing you hope next year goes better for?",
    "December 14 - What smell instantly reminds you of December?",
    "December 15 - What is your favorite memory from this year so far?",
    "December 16 - What fictional character would give the best holiday gifts?",
    "December 17 - What is something you are genuinely excited for next year?",
    "December 18 - What is your favorite kind of snowy scenery?",
    "December 19 - What is one thing that helps you feel motivated again?",
    "December 20 - What is the best part about long winter nights?",
    "December 21 - What is one random thing you want to learn next year?",
    "December 22 - What fictional holiday celebration would you want to attend?",
    "December 23 - What is your favorite thing about relaxing during winter break?",
    "December 24 - What small thing always improves holiday gatherings?",
    "December 25 - What is one gift you would love to receive regardless of price?",
    "December 26 - What is your favorite kind of post-holiday relaxation?",
    "December 27 - What is one thing you want less of in your life next year?",
    "December 28 - What is one thing you definitely want more of next year?",
    "December 29 - What is your ideal New Year's Eve vibe?",
    "December 30 - What is something you learned about yourself this year?",
    "December 31 - What is one goal or mindset you want to carry into next year?"
];
